{% set version = "1.4-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bpca
  version: "{{ version|replace("-", "_") }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/bpca_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bpca/bpca_{{ version }}.tar.gz
  sha256: 96937d9ab3b53e8939ef3e91c838ac70bdac0eb9f12dcd0bbe0ad6bc40a27983

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rgl
    - r-scatterplot3d
    - r-xtable
  run:
    - r-base
    - r-rgl
    - r-scatterplot3d
    - r-xtable

test:
  commands:
    - LD_LIBRARY_PATH="${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib" $R -e "library('bpca')"  # [not win]
    - "\"%R%\" -e \"library('bpca')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bpca
  dev_url: https://github.com/jcfaria/bpca
  license: GPL-2.0-only
  summary: Provides tools for creating 2D and 3D biplots of multivariate data based on principal
    components analysis, together with diagnostics for reduction quality and enhanced
    visualization of variables and objects.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
