appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fCekIkVrc7pDbAqc21UJN3uPcZDOtj9X4ivCEmJO2VAP3WieI3ufWu8Tipquv3bL2DiOQCDUpEwxBl+pFIBYRAqHLh5a7EXjJpAatGv5P437G6FnDWnKHLl139jBZcE3qEt1cTI6Bik5jtU1n79136fvVFYJr/I3QfU/ybAecU4/NfgfnVmVVRoC++okCpqU2ZNwRGpwC4MDqtvp/Vp4lK97rt8wkNCxYn1nePfFsmEcwK1bLSk6dyNNr9znaEzzEJibxTkCfHOIojU/ZSPs0/m2Pi/AlETw8rEOjOHGUK+GGNI2uB+qE9lvAR3EsIgbWYRJ7aB7BoPOAn/e4g3n9U+7up2WZoKxy2q+ZNZ5RJyxokPH/ssYySkrA7vaNs6dmCdf1fQrVzJkhSAOvHKeVtDQGB2o0znwXus1KIBq/ONy5zsX7rtXFbQGEtuzrZvd+AoN9zLbnxuLS7hvsxPNklgOJRVYyoV8tTxW4XvzGGDSd9DbSMEc7a6327G8svqKlBh5k3Ura7aC68vpgnfUDAZ5C5juxymwTZmlBL4fH9hSCy83gsu2xyrugDcjw87TYBaiTjVl6aXxGbQ0Ww86PS5Rpe5DQs3KGHVEbO764EfIzg8XVv8/DxRaQo1g4Wwwnwf9sp+IROdq+UPtSNh8QRfTrzEsHRGhDVnD5ZlM5AA=
conda_forge_output_validation: true
